export const TileType = {
  BLANK: "blank",
  ARROW_UP: "arrow_up",
  ARROW_DOWN: "arrow_down",
  ARROW_LEFT: "arrow_left",
  ARROW_RIGHT: "arrow_right",
  DOUBLE_ARROW_UP: "double_arrow_up",
  DOUBLE_ARROW_DOWN: "double_arrow_down",
  DOUBLE_ARROW_LEFT: "double_arrow_left",
  DOUBLE_ARROW_RIGHT: "double_arrow_right",
  BLOCK: "block",
  CRACKED: "cracked",
  DRILL: "drill",
  HOLE: "hole",
  WALL: "wall",
};